name: CI for Past Exam

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_unit_test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install NPM Dependencies
      run: npm install
    - name: Run Unit Tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "stilqnchanev"

  run_ui_tests:

    runs-on: ubuntu-latest
    needs: build_and_unit_test
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install NPM Dependencies
      run: npm install
    - name: Run Application
      run: npm run start &
    - name: Install Playwright
      run: npx playwright install
    - name: Run UI Tests
      run: npm run test:ui